const data = {
  products: [
    {
      _id: '1',
      name: 'Lalalla',
      category: 'Cup Corn',
      image: '/images/p1.jfif',
      price: 120,
      countInStock: 10,
      brand: 'Del Monte',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Corn Cob',
      category: 'Cobs',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Del Monte',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'PopCorn',
      category: 'PopCorn',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Shine',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Roasted Corn',
      category: 'Cobs',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Shine',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Corn Flakes',
      category: 'Corn Flakes',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Shine',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Flint Corn',
      category: 'Cobs',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Del Monte',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
export default data;
